-- MySQL Script generated by MySQL Workbench
-- Sun 05 Apr 2020 12:47:16 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WebDiP2019x144
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2019x144
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2019x144` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2019x144` ;

-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`uloga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`uloga` (
  `uloga_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`uloga_id`))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`status_id`))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`korisnik` (
  `korisnik_id` INT NOT NULL AUTO_INCREMENT,
  `id_uloga` INT NOT NULL,
  `id_status` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `slika` TEXT NOT NULL,
  `korisnicko_ime` VARCHAR(25) NOT NULL,
  `lozinka` VARCHAR(25) NOT NULL,
  `lozinka_sha1` CHAR(40) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `uvjeti` TINYINT(1) NULL,
  `linkAktivacije` TEXT NULL,
  `blokiranDo` DATETIME NULL,
  PRIMARY KEY (`korisnik_id`),
  INDEX `fk_korisnik_uloga_idx` (`id_uloga` ASC),
  INDEX `fk_korisnik_status1_idx` (`id_status` ASC),
  CONSTRAINT `fk_korisnik_uloga`
    FOREIGN KEY (`id_uloga`)
    REFERENCES `WebDiP2019x144`.`uloga` (`uloga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_korisnik_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `WebDiP2019x144`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`tip` (
  `tip_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`tip_id`))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`dnevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`dnevnik` (
  `dnevnik_id` INT NOT NULL AUTO_INCREMENT,
  `id_korisnik` INT NOT NULL,
  `id_tip` INT NOT NULL,
  `radnja` TEXT NOT NULL,
  `upit` TEXT NOT NULL,
  `vrijeme` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dnevnik_id`, `id_korisnik`, `id_tip`),
  INDEX `fk_dnevnik_korisnik1_idx` (`id_korisnik` ASC),
  INDEX `fk_dnevnik_tip1_idx` (`id_tip` ASC),
  CONSTRAINT `fk_dnevnik_korisnik1`
    FOREIGN KEY (`id_korisnik`)
    REFERENCES `WebDiP2019x144`.`korisnik` (`korisnik_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dnevnik_tip1`
    FOREIGN KEY (`id_tip`)
    REFERENCES `WebDiP2019x144`.`tip` (`tip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`postavke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`postavke` (
  `postavke_id` INT NOT NULL AUTO_INCREMENT,
  `id_administratora` INT NOT NULL,
  `stranicenje` INT NOT NULL,
  `trajanjeKolacica` TIME NULL,
  `tema` VARCHAR(15) NULL,
  `bojaPozadine` CHAR(7) NULL,
  `velicinaFonta` INT NOT NULL,
  `bojaFonta` CHAR(7) NULL,
  PRIMARY KEY (`postavke_id`),
  INDEX `fk_postavke_korisnik1_idx` (`id_administratora` ASC),
  CONSTRAINT `fk_postavke_korisnik1`
    FOREIGN KEY (`id_administratora`)
    REFERENCES `WebDiP2019x144`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`drzava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`drzava` (
  `drzava_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(35) NOT NULL,
  `produzeniOblik` VARCHAR(70) NULL,
  `skraceniOblik` VARCHAR(7) NOT NULL,
  `clanEU` TINYINT(1) NULL,
  PRIMARY KEY (`drzava_id`))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`postanskiUred`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`postanskiUred` (
  `postanskiUred_id` INT NOT NULL AUTO_INCREMENT,
  `id_moderatora` INT NOT NULL,
  `id_drzave` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(60) NOT NULL,
  `postanskiBroj` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`postanskiUred_id`),
  INDEX `fk_postanskiUred_korisnik1_idx` (`id_moderatora` ASC),
  INDEX `fk_postanskiUred_drzava1_idx` (`id_drzave` ASC),
  CONSTRAINT `fk_postanskiUred_korisnik1`
    FOREIGN KEY (`id_moderatora`)
    REFERENCES `WebDiP2019x144`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postanskiUred_drzava1`
    FOREIGN KEY (`id_drzave`)
    REFERENCES `WebDiP2019x144`.`drzava` (`drzava_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`posiljka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`posiljka` (
  `posiljka_id` INT NOT NULL AUTO_INCREMENT,
  `id_posiljatelja` INT NOT NULL,
  `id_primatelja` INT NOT NULL,
  `id_konacniUred` INT NULL,
  `id_trenutniUred` INT NULL,
  `spremnaZaIsporuku` TINYINT(1) NOT NULL,
  `cijenaPoKg` DOUBLE NULL,
  `masa` DOUBLE NOT NULL,
  PRIMARY KEY (`posiljka_id`),
  INDEX `fk_posiljka_korisnik1_idx` (`id_posiljatelja` ASC),
  INDEX `fk_posiljka_korisnik2_idx` (`id_primatelja` ASC),
  INDEX `fk_posiljka_postanskiUred1_idx` (`id_konacniUred` ASC),
  INDEX `fk_posiljka_postanskiUred2_idx` (`id_trenutniUred` ASC),
  CONSTRAINT `fk_posiljka_korisnik1`
    FOREIGN KEY (`id_posiljatelja`)
    REFERENCES `WebDiP2019x144`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posiljka_korisnik2`
    FOREIGN KEY (`id_primatelja`)
    REFERENCES `WebDiP2019x144`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posiljka_postanskiUred1`
    FOREIGN KEY (`id_konacniUred`)
    REFERENCES `WebDiP2019x144`.`postanskiUred` (`postanskiUred_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posiljka_postanskiUred2`
    FOREIGN KEY (`id_trenutniUred`)
    REFERENCES `WebDiP2019x144`.`postanskiUred` (`postanskiUred_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WebDiP2019x144`.`racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2019x144`.`racun` (
  `racun_id` INT NOT NULL AUTO_INCREMENT,
  `id_posiljke` INT NOT NULL,
  `vrijemeIzdavanja` DATETIME NOT NULL,
  `placen` TINYINT(1) NOT NULL,
  `iznos` DOUBLE NOT NULL,
  `puniIznos` DOUBLE NOT NULL,
  `slika` TEXT NULL,
  PRIMARY KEY (`racun_id`, `id_posiljke`),
  INDEX `fk_racun_posiljka1_idx` (`id_posiljke` ASC),
  CONSTRAINT `fk_racun_posiljka1`
    FOREIGN KEY (`id_posiljke`)
    REFERENCES `WebDiP2019x144`.`posiljka` (`posiljka_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
